#!/bin/bash

set -e

SCRIPT_NAME=$(basename $0)

KEY=$1

[ -z "${KEY}" ] && echo "${SCRIPT_NAME} <PGP Key>" 1>&2 && exit 1

agent_info=/var/run/reprepro_watch/gpg-agent.env
if [ -z "${GPG_AGENT_INFO}" ] && [ -e "${agent_info}" ]; then
    export $(cat ${agent_info})
fi;

if [ -z "${GPG_AGENT_INFO}" ]; then
    echo "GPG_AGENT_INFO environment variable is not set, cannot continue" 1>&2
    exit 1
fi;

# get original stty setting
stty_orig=`stty -g`

function cleanup
{
    stty $stty_orig
}

trap cleanup SIGINT


# disable echo
stty -echo

homedir=$(echo ${GPG_AGENT_INFO} | sed 's,\(.*\)/.*,\1,')
for fingerprint in $(gpg --fingerprint --fingerprint "${KEY}" | grep fingerprint | sed -e 's/.*=\(.*\)/\1/' -e 's/ //g'); do
    echo "fingerprint: ${fingerprint}, homedir: ${homedir}"
    /bin/echo -n "Type in or paste your passphrase:"
    /usr/lib/gnupg2/gpg-preset-passphrase --homedir=${homedir} --preset ${fingerprint}
    /bin/echo ''
done;

cleanup
